name: baseline_icra19

train_data_path: /mnt/work2/Trinity_Gesture_DB/lmdb/lmdb_train
val_data_path: /mnt/work2/Trinity_Gesture_DB/lmdb/lmdb_test

wordembed_dim: 300
wordembed_path: ../resource/crawl-300d-2M-subword.bin  # fasttext

model_save_path: ../output/train_seq2seq
random_seed: 0

data_mean: [0.99414, 0.05276, -0.01830, -0.05399, 0.98730, -0.07916, 0.01263, 0.07880, 0.99316, 1.00000, 0.01767, 0.00634, -0.01717, 0.99854, -0.07086, -0.00766, 0.07074, 0.99854, 0.99951, 0.01764, -0.00896, -0.01765, 1.00000, 0.00019, 0.00896, -0.00005, 0.99951, 1.00000, -0.00739, -0.01461, 0.00706, 1.00000, -0.01138, 0.01510, 0.01107, 1.00000, 0.99805, 0.00925, 0.00102, -0.00964, 0.98096, -0.17590, -0.00240, 0.17456, 0.97949, 0.98926, 0.00434, -0.03925, -0.00249, 0.99951, 0.02534, 0.03946, -0.02550, 0.98828, 1.00000, 0.00189, -0.00242, -0.00105, 0.95752, 0.27734, 0.00261, -0.27759, 0.95801, 0.95410, -0.02214, -0.23987, 0.02150, 0.98584, 0.00000, 0.23657, 0.00037, 0.96777, 0.36108, -0.81299, 0.27588, 0.80957, 0.37817, 0.16406, -0.24243, 0.15540, 0.83447, 0.05392, -0.22961, 0.67334, 0.00002, 0.81055, 0.23083, -0.84521, 0.07886, 0.07214, 0.92676, -0.23047, -0.09564, 0.22668, 0.93848, -0.03152, 0.10413, 0.00001, 0.98828, 0.96338, -0.00713, 0.21875, 0.00795, 0.99023, -0.00000, -0.21655, 0.00461, 0.97363, 0.30835, 0.78467, -0.42993, -0.84326, 0.37915, 0.11230, 0.26318, 0.34448, 0.80078, 0.09741, 0.21948, -0.67285, -0.00000, 0.80664, 0.21936, 0.85010, 0.04178, 0.10510, 0.93457, 0.19019, -0.00217, -0.18896, 0.94238, -0.00727, 0.00069, 0.00001, 0.99219]
data_std: [0.08801, 0.03111, 0.01127, 0.03111, 0.08801, 0.03806, 0.01147, 0.03815, 0.08801, 0.08801, 0.00571, 0.00195, 0.00560, 0.08801, 0.01682, 0.00254, 0.01680, 0.08801, 0.08801, 0.00809, 0.01999, 0.00826, 0.08801, 0.00847, 0.02000, 0.00852, 0.08801, 0.08801, 0.01180, 0.00590, 0.01175, 0.08801, 0.00827, 0.00601, 0.00827, 0.08801, 0.08801, 0.01738, 0.02643, 0.01482, 0.08801, 0.04764, 0.02838, 0.04758, 0.08801, 0.08801, 0.01122, 0.06299, 0.01103, 0.08801, 0.01845, 0.06305, 0.01826, 0.08801, 0.08801, 0.01365, 0.00780, 0.01556, 0.08801, 0.04874, 0.00441, 0.04880, 0.08801, 0.08801, 0.04425, 0.04453, 0.04507, 0.08801, 0.00000, 0.04440, 0.01525, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08813, 0.08801, 0.08801, 0.08844, 0.08801, 0.00055, 0.08801, 0.08923, 0.08801, 0.08533, 0.08801, 0.08801, 0.08508, 0.04401, 0.07373, 0.08801, 0.02698, 0.04498, 0.00000, 0.08801, 0.08801, 0.03989, 0.04425, 0.04178, 0.08801, 0.00000, 0.04410, 0.01121, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.08807, 0.08801, 0.00042, 0.08801, 0.09247, 0.08801, 0.08801, 0.08801, 0.08801, 0.08801, 0.04617, 0.08801, 0.08801, 0.02463, 0.04758, 0.00024, 0.08801]

# model params
model: seq2seq
hidden_size: 200
n_layers: 2
dropout_prob: 0.1

# train params
epochs: 100
batch_size: 128
learning_rate: 0.0005
loss_l1_weight: 5
loss_cont_weight: 0.1
loss_var_weight: 0.5

# dataset params
motion_resampling_framerate: 20
n_poses: 30
n_pre_poses: 10
subdivision_stride: 10
loader_workers: 4
